//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public int custid { get; set; }
        public string cuscode { get; set; }
        public string cusname { get; set; }
    }
}
